version: '3.3'
services:
    demo-pgadmin4: 
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: testes@gmail.com
            PGADMIN_DEFAULT_PASSWORD: testes
        ports: 
            - 7171:80
        networks: 
            - deploy

    redis:
        image: redis
        command: redis-server --requirepass redispass123
        container_name: redis
        environment: 
            - REDIS_PORT=6379
            - REDIS_PASSWORD=redispass123
        
        networks:
            - deploy
        volumes:
            - ./redis-data:/var/lib/redis

    postgres:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=kodekonan
            - POSTGRES_DB=kopishop
        networks: 
            - deploy
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    nodejs:
        image: endaafiandika/food-backend
        ports:
            - 4000:4000
        depends_on:
            - postgres
            - redis    
        networks:
            - deploy
        environment: 
            - DB_USER=postgres
            - DB_DATABASE=kopishop
            - DB_PASS=cahbacem2012
            - DB_HOST=postgres
            - REDIS_HOST=redis
            - REDIS_PASS=redispass123
            - REDIS_PORT=6379
            - JWT_KEYS=regdfgdfgdfg

networks:
    deploy:
        driver: bridge
    
volumes:
    postgres-data:
    redis-data:
